<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <script>
    
    function resolveAfter2S (x) {
        return new Promise((resovle, reject) => {
            setTimeout(function () {
                if (x < 50) {
                    resovle(x);
                    console.log('resolved');
                } else {
                    reject(x);
                    console.log('rejected');
                }
            }, 2000);
        });
    }

    /**
    * promise 的链式调用
    * 在一个promise的结果里return一个promise, 则后面可以继续用 then 捕获结果, 
    * 如果有一个执行了reject, 在可以在最后的catch里捕获到, 同时reject后面的promise不会执行
    */
    const p1 = resolveAfter2S(10)

    p1.then(res => {
        console.log(1, res)
        return resolveAfter2S(20)
    })
    .then(res => {
        console.log(2, res)
        return resolveAfter2S(70)
    })
    .then(res => {
        console.log(3, res)
        return resolveAfter2S(30)
    })
    .then(res => {
        console.log(4, res)
    })
    .catch(err => {
        console.log('catch:', err)
    })

    // 利用generator
    function * generatorState () {
        yield resolveAfter2S(10)
        yield resolveAfter2S(20)
        yield resolveAfter2S(30)
    }

    const sg = generatorState()
    
    for (val of sg) {
        console.log('generatorState:', val)
    }
    
    

    </script>
</body>
</html>